import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AOSProvider from "@/components/AOSProvider";
import Header from "@/components/sections/Header";
import Footer from "@/components/sections/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AOSProvider />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
